backend:
  name: github
  repo: puck3000/redux-vuepress
  branch: master

public_folder: "/assets/img"
media_folder: "docs/.vuepress/dist/assets/img"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "docs"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Titelbild", name: "heroImg", widget: "image"}
      - {label: "Bildunterschrift", name: "bildunterschrift", widget: "string"}
      - {label: "Inhalt", name: "inhalt", widget: "markdown"}

